
server:
  port: ":65000"

database:
  uri: "host=nlbook.net dbname=users sslmode=disable user=postgres password=8093 port=5432"

token:
  secret_key: "test_secret_key"
  public_key: "test_public_key"
  salt: "salt"

logger:
  log_level: "info"
